kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.ReplicaNumber }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
        - name: index-html
          configMap:
            name: '{{ .Chart.Name }}-html'
            defaultMode: 420
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.containers.containerPort }}
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
          volumeMounts:
          - name: index-html
            mountPath: /tmp/html
          readinessProbe:
            httpGet:
              path: /health/readiness # this check the application url path
              port: {{ .Values.containers.containerPort  }} # In which port the Application is listening
              scheme: HTTP
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }} # the time is waiting befor testing the application path
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }} # the time for timeout
            periodSeconds: {{ .Values.probes.periodSeconds }} # the abount of time to wait between checks
            successThreshold: {{ .Values.probes.successThreshold }} # count to decalre seccessfull 
            failureThreshold: {{ .Values.probes.failureThreshold }} # count to decalre failure 
          livenessProbe:
            httpGet:
              path: /health/liveliness
              port: {{ .Values.containers.containerPort }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }} # the time is waiting befor testing the application path
            timeoutSeconds: {{ .Values.provvgggbes.timeoutSeconds }} # the time for timeout
            periodSeconds: {{ .Values.probes.periodSeconds }} # the abount of time to wait between checks
            successThreshold: {{ .Values.probes.successThreshold }} # count to decalre seccessfull 
            failureThreshold: {{ .Values.probes.failureThreshold }} # count to decalre failure 
          env:
            - name: PORT
              value: {{ .Values.containers.containerPort | quote }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10